# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 701f08e16ec9e1ca5c4db0d00f151fde8599cd82abe24cfb846462e1cac71940a6df1129bc5b9db66d16a30722ceb2176801099bd965c4737a692c3c22534a8a

test:
  secret_key_base: bbcc48d9c3bda7785c303e0cba6e105e8993ba593d4c31424cb18f2c82d4fc08c3bd2b1932f95931d5414c93f4cc0721197688921b41b4e8d830f22a1dd20934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
